Not Found: /favicon.ico
Not Found: /saludo
Not Found: /saludo/
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /saludo
Not Found: /favicon.ico
Not Found: /saludo
Not Found: /favicon.ico
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Internal Server Error: /saludo
Traceback (most recent call last):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 52, in process_request
    if self.should_redirect_with_slash(request):
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/middleware/common.py", line 70, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 540, in resolve
    for pattern in self.url_patterns:
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/virupqhv/virtualenv/futbol/3.5/lib/python3.5/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/opt/alt/python35/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/virupqhv/futbol/project/urls.py", line 18, in <module>
    from project.views import saludo
  File "/home/virupqhv/futbol/project/views.py", line 1, in <module>
    from django.hhtp import HttpResponse
ImportError: No module named 'django.hhtp'
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /shGlVnXYqTelhu
Not Found: /
Not Found: /xztPCvpDvPrb.php
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /
Not Found: /favicon.ico
Not Found: /
